/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 26.04.2026 10:45:06

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 16
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 42512;
#else
constexpr int kTensorArenaSize = 41488;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 99, 40, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data2[2] = { -1, 168, };
const TfArray<1, int> tensor_dimension2 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[8] = { 1335, -344, -1556, -1116, 2266, 187, -957, -1346, };
const TfArray<1, int> tensor_dimension3 = { 1, { 8 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00031203345861285925, } };
const TfArray<1, int> quant3_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[8*168] = { 
  -71, 22, -73, -16, 25, -11, -27, -39, -20, -22, 17, 1, -39, 18, 12, -10, -2, -24, 1, -8, -6, -4, -14, 5, -50, 6, -43, -3, 18, 8, -9, -29, -4, -24, 16, 9, -26, 6, 11, -21, 8, -27, -1, -4, -2, 3, 2, 12, -59, 19, -31, 0, 18, -7, -6, -30, -7, -22, 14, 6, -34, 6, 8, -16, -2, -39, 5, 3, -5, -2, 9, -5, -52, 25, -40, -24, 24, -13, -11, -32, -11, -37, 8, 11, -21, 15, 7, -21, -3, -36, -3, 2, -3, -8, 11, -6, -46, 21, -43, -11, 10, -10, -18, -17, -10, -29, 6, 14, -17, 10, 2, -17, 5, -12, 3, -8, -7, 9, 5, 8, -51, 23, -33, 7, 3, 7, -27, -35, -9, -21, 6, 4, -13, 3, 17, -17, 2, -37, -2, -6, -12, -3, 7, 5, -36, 6, -37, -5, 5, -8, -35, -26, -9, -28, -6, 13, -13, 0, 1, -19, 9, -27, -7, 5, -8, -4, 9, 13, 
  42, -66, 22, 41, -52, 40, 16, 57, -4, 6, -2, -5, -23, -1, -17, 14, -20, -13, -1, -3, -6, -4, 19, -17, 45, -85, 12, 29, -38, 34, 24, 50, 4, 11, 3, 2, -10, -11, -5, 1, -9, 1, -2, -1, -13, -2, 12, -2, 40, -82, 17, 25, -46, 22, 12, 49, 3, 12, 7, 2, -33, -5, -14, 9, -13, -5, 5, 3, -8, -5, 9, -13, 46, -58, 35, 25, -46, 20, 29, 53, -2, 7, 4, 5, -26, 1, -7, 2, -11, -20, -1, 0, -3, -6, 12, -15, 36, -53, 20, 26, -43, 25, 15, 39, 1, -1, -5, 6, -25, -8, -18, 0, -3, 3, 8, -6, -12, 11, 27, -1, 49, -39, 8, 29, -36, 27, 8, 37, -2, 18, -6, -4, -25, -16, -7, 1, -9, -3, 3, -4, -15, 1, 25, -6, 67, -48, 2, 24, -30, 38, 13, 84, 4, 4, -22, 6, -29, -17, -19, -10, -15, -6, -5, -3, -5, -11, 3, -12, 
  17, -66, -34, 3, -71, -19, 14, 41, 2, 15, 17, -1, 43, 16, -3, 16, -2, 13, -4, -9, -21, -8, -18, 2, 32, -70, -31, 3, -58, -19, 22, 38, 11, 2, 18, 4, 46, 6, 4, 7, 4, 9, 0, -5, -14, 3, -7, 7, 21, -61, -23, 2, -68, -30, 18, 39, 13, 9, 14, 4, 54, 7, -4, 12, -4, 13, 3, -2, -8, -2, -4, -4, 26, -75, -10, -6, -78, -29, 28, 41, 8, 4, 10, 7, 56, 14, 1, 11, -6, 13, -10, -8, -8, -10, -7, -8, 20, -55, -22, 11, -72, -17, 26, 26, 7, -16, 9, 9, 49, 8, -4, 9, 4, 21, -1, -16, -10, 10, 0, 1, 29, -34, -32, 14, -69, -12, 13, 26, 5, -11, 4, -1, 58, 0, 11, 2, -2, 3, -3, -11, -13, 0, 5, 1, 32, -51, -38, 12, -71, -29, 6, 34, 11, -34, -1, 8, 32, -1, -7, 1, 3, -12, -21, -6, -8, -8, -6, 6, 
  -7, -38, -1, -45, -58, -62, -44, 24, -4, 16, 19, 4, -7, 19, 11, 10, 0, 47, 4, -1, -7, 2, -26, 6, 3, -57, 10, -44, -62, -35, -29, 11, 7, -9, 15, 8, -2, 7, 11, 2, 7, 58, 7, -2, -7, 5, -21, 10, 3, -37, 3, -38, -59, -55, -26, 19, 6, -4, 14, 6, 6, 6, 6, 9, -3, 49, 9, 4, -2, 1, -29, -4, -1, -48, 16, -44, -66, -50, -29, 23, 2, -6, 10, 11, 0, 14, 9, 2, -3, 52, 2, 4, -4, -6, -16, -6, 3, -28, 4, -39, -60, -41, -36, 14, 3, -22, 8, 13, -2, 9, 3, -3, 4, 65, 8, -4, 1, 14, -8, 7, 12, -28, -4, -27, -70, -46, -32, 15, -1, -7, 5, 4, 4, 2, 16, -2, 3, 32, 2, 1, -5, 2, -19, 4, -16, -34, -4, -33, -55, -70, -25, 23, 4, 7, -5, 15, -3, 0, 1, -10, 9, 44, 1, 5, 0, -2, -16, 13, 
  -103, 20, -98, -107, 31, -122, -60, -54, -82, 16, -12, -98, 16, 6, -37, -53, -5, 24, -19, -77, 14, 6, -67, 3, -122, 18, -82, -60, 38, -71, -37, -45, -20, 16, -9, -71, 24, -2, -17, -17, 2, 19, -15, -50, 25, 11, -95, 3, -113, 33, -19, -78, 39, -47, -7, -32, -35, 21, -26, -66, 22, -8, -16, -18, -17, 11, 4, -36, 31, 13, -82, -13, -110, 31, -37, -56, 44, -53, -44, -46, -56, 23, -25, -70, 24, 0, -19, -31, -5, 16, -22, -45, 26, 3, -96, -9, -117, 32, -56, -79, 30, -60, -38, -25, -28, 11, -23, -84, 25, -5, -27, -12, -3, 31, -14, -66, 16, 18, -63, -4, -117, 30, -86, -83, 20, -60, -13, -44, -23, 20, -30, -63, 27, 4, -14, -7, -12, 10, -10, -34, 15, 15, -71, -8, -94, 18, -116, -110, 22, -89, -69, -79, -35, 21, -32, -66, 14, -4, -18, -22, -9, 17, -4, -28, 25, 13, -85, -14, 
  -60, 18, -29, -15, 21, -7, -32, -38, -17, -3, -11, 7, -35, 14, 19, -5, -23, -25, 3, 2, 13, 1, 7, -26, -21, 9, -11, -13, 23, 5, -25, -10, -4, -42, 1, 11, -65, 1, 18, -5, -14, -60, 0, 1, 18, 5, 15, -19, -26, 28, -3, 5, 35, 26, -9, -23, -6, -23, -5, 10, -30, 3, 12, 0, -23, -33, 5, 11, 17, 1, 2, -27, -8, 20, 1, -14, 39, 21, -26, -6, -22, -26, -11, 11, -53, 16, 11, -34, -27, -37, -3, 6, 16, -7, -3, -29, -12, 29, -27, -26, 31, 4, -34, 30, -20, -53, -23, 14, -98, 4, 5, -22, -23, -57, 2, -3, 11, 11, 18, -33, -8, 30, -30, -20, 21, -1, -39, 18, -25, -9, -9, 5, -76, -7, 22, -30, -25, -46, 1, 3, 17, 3, 14, -37, -12, 12, -37, 10, 16, 14, -23, -6, -9, 2, -17, 14, -34, -14, 1, 2, -16, -12, -6, 4, 20, -1, -5, -26, 
  -26, -4, 1, -3, -3, 14, 5, -26, -8, -15, 18, 3, -27, 19, 12, 1, 0, -24, -2, -14, -15, -10, 20, 5, -7, -7, 13, 3, 1, 18, 19, -27, 4, -18, 17, 8, -9, 8, 11, 0, 7, -22, -1, -11, -7, -4, 28, 10, -16, 7, 13, -1, 13, 6, 11, -18, 2, 4, 13, 6, -13, 7, 5, 3, -1, -22, 3, 0, -1, -6, 26, -4, -13, 8, 19, -7, 13, 6, 13, -22, -3, -2, 10, 9, -2, 15, 8, -7, -3, -18, -6, -4, -5, -10, 34, -6, -2, 12, 7, -3, 7, 9, 11, -23, 1, -32, 6, 11, -14, 9, 2, -2, 6, -17, -1, -15, -4, 7, 27, 6, -2, 4, 5, 8, 0, 14, 5, -24, -4, -11, 6, 3, -4, 3, 17, -3, 3, -24, -3, -8, -7, -3, 21, 5, -42, -23, 14, 0, -2, 12, 3, -37, 0, -8, -4, 15, -6, 2, 1, -17, 6, -24, -8, -3, 1, -9, 26, 12, 
  -34, -4, 53, 41, 21, 59, 44, -64, 6, 15, -43, -37, 16, -55, -15, 20, -19, 15, -17, -24, -7, -51, -127, -19, -27, -5, 25, 28, 12, 39, 32, -66, 7, 17, -38, -37, 25, -59, 0, 6, -10, 21, -1, -11, 1, -26, -98, -8, -25, 15, 35, 25, 10, 25, 22, -52, 6, 25, -36, -31, 23, -51, 10, 12, -13, 16, 11, 13, 10, -22, -93, -19, -22, 11, 52, 20, 14, 25, 45, -61, 4, 32, -46, -23, 13, -44, 13, 7, -6, 16, 0, 3, 2, -30, -88, -15, -29, 13, 37, 21, 17, 31, 20, -67, 7, 26, -33, -22, 18, -49, -5, 5, 1, 31, 4, -14, 4, -10, -98, -2, -18, 4, 39, 33, 3, 39, 25, -78, 3, 29, -22, -27, 10, -46, 6, 8, 6, 6, -2, -10, -4, -17, -100, 5, -26, -12, 59, 37, 13, 59, 38, -72, 23, 11, -40, -26, -1, -53, -2, 19, 13, 12, 15, -25, 1, -32, -106, 0, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 8,168 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0080940872430801392, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[8] = { -1547, 4363, -4185, -994, 3215, -31, -216, -2227, };
const TfArray<8, float> quant5_scale = { 8, { 4.9552301788935438e-05, 7.3005277954507619e-05, 4.8576839617453516e-05, 7.1255009970627725e-05, 6.8089626438450068e-05, 7.2641283622942865e-05, 6.5002444898709655e-05, 5.1053026254521683e-05, } };
const TfArray<8, int> quant5_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[8*3*3*8] = { 
  /* [0][0][][] */ 82,91,-3,41,101,29,10,105, -5,-7,-24,-4,-2,18,21,14, -14,31,-4,-20,-35,0,5,31, 
  /* [0][1][][] */ 127,121,-6,-8,39,22,-3,79, -10,2,-22,0,2,23,4,18, -16,37,0,-32,-28,4,-1,-8, 
  /* [0][2][][] */ 85,95,-6,3,83,12,5,87, -1,1,-23,3,7,1,-10,12, -13,9,-9,-32,-28,9,9,60, 
  /* [1][0][][] */ -10,-46,-75,-42,-16,63,2,-34, -44,19,-45,-36,-37,46,-15,11, -83,-119,-20,-91,-111,-40,-8,-108, 
  /* [1][1][][] */ -11,-11,-58,-32,0,-3,5,-25, -20,34,-30,-23,-19,52,-9,19, -105,-75,-14,-111,-117,-30,-9,-100, 
  /* [1][2][][] */ -39,-42,-63,-33,-25,90,-17,-28, -45,8,-47,-28,-35,30,-126,21, -127,-117,3,-116,-88,14,-2,-111, 
  /* [2][0][][] */ -35,-1,12,-8,-43,-49,49,14, 50,36,-6,-5,9,29,-60,127, -48,-31,9,-75,-32,28,7,61, 
  /* [2][1][][] */ -33,-8,25,-6,-63,-74,41,-3, 3,81,-14,30,33,37,-14,40, -41,16,1,-20,-52,38,-4,48, 
  /* [2][2][][] */ -52,-20,22,-8,-66,-64,13,3, 28,12,11,-25,30,33,-10,99, -17,11,3,-41,-15,9,3,53, 
  /* [3][0][][] */ -59,-17,23,-1,-59,-113,23,13, 7,-4,84,15,-15,-40,-53,26, 24,10,13,35,19,-29,-17,-2, 
  /* [3][1][][] */ -57,-30,44,6,-68,-127,25,5, -4,45,45,14,5,-52,-40,29, 4,40,10,26,5,-35,-11,3, 
  /* [3][2][][] */ -40,-3,26,5,-32,-79,-2,10, -1,1,55,5,-17,-33,-37,18, 1,19,6,23,4,-32,-12,3, 
  /* [4][0][][] */ -77,-61,-4,-26,-57,27,7,-93, 13,12,2,24,19,76,-116,-6, -98,-95,-13,-103,-121,10,0,-65, 
  /* [4][1][][] */ -53,-92,22,-23,-57,-43,22,-41, 3,14,-3,9,11,-10,-127,-1, -127,-119,-10,-119,-83,-10,-6,-42, 
  /* [4][2][][] */ -73,-37,-2,-17,-51,-8,23,-18, 20,0,-4,13,18,64,-98,2, -115,-126,-11,-120,-107,14,5,-62, 
  /* [5][0][][] */ -47,-18,33,-14,-62,-2,127,20, -4,38,25,38,29,9,-36,13, -24,1,-3,-10,-38,-26,-5,-1, 
  /* [5][1][][] */ -67,-21,16,-20,-72,2,39,35, -5,22,42,16,-6,8,-40,20, -28,1,-1,-4,-23,-24,-4,1, 
  /* [5][2][][] */ -38,-11,18,-1,-52,3,113,22, -8,30,15,3,15,5,-34,1, -2,-1,0,-4,-22,-18,-3,3, 
  /* [6][0][][] */ 23,-13,-35,-40,13,11,43,-10, -74,14,77,-31,-60,-127,80,-25, 21,27,2,3,19,-13,-76,-22, 
  /* [6][1][][] */ 8,-4,-38,-47,22,-5,29,-12, -45,7,76,-11,-64,-126,45,1, 8,-20,1,36,-7,-1,-56,-6, 
  /* [6][2][][] */ 22,-30,-28,-43,4,5,49,-17, -36,10,49,-22,-53,-93,41,-3, 28,47,2,5,-23,-31,-37,-10, 
  /* [7][0][][] */ 79,76,-2,10,127,72,-1,83, -1,3,-10,-1,4,3,10,-3, -3,-4,-27,-15,-8,8,-88,22, 
  /* [7][1][][] */ 56,34,-8,18,68,49,-14,32, -6,-3,-8,1,-2,1,12,10, -2,8,-30,-10,-6,9,22,10, 
  /* [7][2][][] */ 96,69,-4,-5,72,53,-2,56, 1,9,-7,0,2,-7,12,8, 3,16,-20,-10,1,10,-3,11, 
};
const TfArray<4, int> tensor_dimension6 = { 4, { 8,3,3,8 } };
const TfArray<8, float> quant6_scale = { 8, { 0.0036832403857260942, 0.0054265083745121956, 0.0036107341293245554, 0.0052964105270802975, 0.0050611263141036034, 0.0053994529880583286, 0.0048316549509763718, 0.0037947897799313068, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[8] = { 94, 173, -1336, -203, 164, 3259, 118, -1, };
const TfArray<8, float> quant7_scale = { 8, { 3.4040469472529367e-05, 2.4352140826522373e-05, 2.6287672881153412e-05, 3.1023220799397677e-05, 2.5709694455144927e-05, 3.0062419682508335e-05, 3.5419365303823724e-05, 2.8425274649634957e-05, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[8*3*3*8] = { 
  /* [0][0][][] */ 18,46,25,-10,61,25,-37,12, 1,-4,-32,10,-22,41,-24,-5, -82,-111,-12,-69,-91,-22,127,-51, 
  /* [0][1][][] */ 10,9,35,15,-4,40,-37,47, 15,1,-39,36,-8,26,-34,1, -83,-107,-6,-49,-90,-12,55,-60, 
  /* [0][2][][] */ 32,38,18,49,29,-12,-28,43, 20,11,-21,11,1,22,-26,3, -57,-109,-28,-50,-78,-11,109,-55, 
  /* [1][0][][] */ 41,-12,45,5,63,-1,22,44, 34,23,-32,21,38,-19,127,23, -87,-62,-12,-120,-114,-93,62,-116, 
  /* [1][1][][] */ 47,77,17,19,83,17,-6,-14, 4,43,-20,45,7,10,112,32, -89,-83,-18,-99,-42,-89,30,-99, 
  /* [1][2][][] */ -3,74,56,-1,63,-23,0,39, 30,11,-12,28,31,7,110,31, -71,-72,-3,-74,-85,-81,74,-85, 
  /* [2][0][][] */ -27,-9,70,49,74,15,6,2, 49,20,127,57,22,-20,-68,26, -9,58,4,25,23,19,-91,5, 
  /* [2][1][][] */ 6,1,13,-12,46,11,-35,-28, 5,44,84,53,1,10,-61,37, -7,19,-29,46,-9,9,-101,0, 
  /* [2][2][][] */ -4,-13,-4,-34,-10,-6,-45,-42, -9,-13,87,78,45,-10,-61,1, 5,38,2,23,5,-14,-102,-10, 
  /* [3][0][][] */ 37,35,52,127,14,43,-66,81, 9,4,-2,6,-21,69,-42,2, -14,-50,-26,-45,-30,-4,-45,-16, 
  /* [3][1][][] */ 26,-9,69,98,-11,18,-42,-34, 12,36,-10,-13,-5,46,-45,18, -16,-50,-11,-32,3,5,-48,-5, 
  /* [3][2][][] */ -47,-21,35,79,40,52,-3,72, 18,12,-24,9,-19,24,-31,13, -20,-15,-14,-31,18,2,-30,-9, 
  /* [4][0][][] */ 47,12,6,42,63,55,-36,-45, 11,-5,-47,7,-15,43,-7,0, -78,-120,-67,-101,-127,-31,122,-113, 
  /* [4][1][][] */ 38,-9,25,93,4,50,-12,79, 2,4,-31,-6,-16,19,-22,5, -68,-102,-76,-59,-104,-10,33,-100, 
  /* [4][2][][] */ 39,73,37,14,32,72,-23,46, 21,7,-36,4,-5,26,-22,7, -58,-105,-76,-42,-92,-4,94,-58, 
  /* [5][0][][] */ 23,-78,-88,-25,-25,45,77,31, -39,-9,-76,-104,-52,-33,39,-70, -45,-44,-66,-66,6,-2,104,-3, 
  /* [5][1][][] */ 68,18,-64,-21,-17,127,86,37, -46,5,-78,-75,-56,-85,22,-65, -42,-31,-61,-41,15,-17,82,0, 
  /* [5][2][][] */ 46,-53,-35,-23,18,24,68,-16, -36,7,-86,-65,-42,-15,5,-54, -16,-14,-59,-60,6,-10,84,5, 
  /* [6][0][][] */ -92,-120,-88,-107,-116,-109,25,-83, 9,-1,33,-19,0,0,50,14, 56,19,-7,37,-1,47,49,26, 
  /* [6][1][][] */ -119,-102,-68,-127,-85,-118,50,-116, 41,-13,14,15,37,9,17,16, 1,13,-3,-2,11,39,19,-15, 
  /* [6][2][][] */ -118,-50,-76,-95,-49,-102,7,-65, 15,16,-1,25,15,5,17,0, 11,2,53,-1,-6,9,51,50, 
  /* [7][0][][] */ 37,59,15,-14,-6,-31,55,109, 12,8,-45,-5,-4,-36,127,-8, -13,-14,-1,-76,12,-98,81,-18, 
  /* [7][1][][] */ 49,70,44,10,50,-64,64,11, 27,-15,-32,-21,18,10,81,12, -5,-9,12,-53,-9,-99,23,-29, 
  /* [7][2][][] */ 47,-15,16,-32,101,-49,87,19, 13,-5,-43,-33,15,-37,97,-7, -20,5,-1,-54,12,-84,64,5, 
};
const TfArray<8, float> quant8_scale = { 8, { 0.0050243507139384747, 0.0035943600814789534, 0.0038800432812422514, 0.0045790071599185467, 0.0037947339005768299, 0.0044371932744979858, 0.0052278749644756317, 0.0041955518536269665, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[8] = { -342, -9337, -4849, 41, -1440, -37, -1046, -117, };
const TfArray<8, float> quant9_scale = { 8, { 1.5700679796282202e-05, 1.1758586879295763e-05, 1.7396163457306102e-05, 1.6049394616857171e-05, 1.2558585694932844e-05, 1.6881333067431115e-05, 1.8713293684413657e-05, 1.5698153220000677e-05, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[8*3*3*8] = { 
  /* [0][0][][] */ 127,79,34,-25,52,113,39,38, 47,32,13,23,67,29,-15,20, -17,-9,26,-37,-16,-56,-61,-30, 
  /* [0][1][][] */ 72,85,6,-8,24,-47,0,60, 38,-13,5,-14,54,39,22,12, -1,-10,14,-21,-5,-56,-19,-23, 
  /* [0][2][][] */ 88,70,5,-46,51,117,44,21, 24,-12,-9,-63,38,38,-42,-17, -36,-2,13,10,-11,-48,-39,-29, 
  /* [1][0][][] */ -12,124,-5,3,25,125,56,88, 16,-17,5,48,57,37,77,31, 56,-36,24,-61,-31,-81,3,-31, 
  /* [1][1][][] */ 65,86,-2,67,44,81,127,55, 113,-10,17,-61,47,-25,-48,29, 35,-32,18,31,-23,-72,10,-29, 
  /* [1][2][][] */ 23,80,-44,116,48,45,23,-10, -29,-67,-17,7,116,24,17,46, 55,-80,34,-113,13,-81,73,-40, 
  /* [2][0][][] */ 24,38,-19,-33,-48,30,11,52, 5,45,-39,54,25,82,26,-18, 54,29,7,3,2,-15,57,16, 
  /* [2][1][][] */ 78,37,-31,-59,-55,5,71,26, 14,18,-32,66,26,-17,-1,22, -2,-2,1,67,-1,-32,16,5, 
  /* [2][2][][] */ 43,63,-31,1,-74,11,-11,30, -9,51,-22,127,29,54,64,38, 0,77,6,-35,-42,-25,8,-17, 
  /* [3][0][][] */ 76,-3,-5,91,31,-12,5,100, 62,40,-4,50,-23,-6,46,-35, -7,-4,2,25,-5,-11,-14,-13, 
  /* [3][1][][] */ 66,102,-7,1,-12,21,27,69, 7,-5,-17,61,-13,1,9,32, 9,-10,10,13,5,-23,-6,-8, 
  /* [3][2][][] */ 66,92,-12,127,-2,23,6,-40, -4,13,-28,4,-39,-2,-5,-22, 2,-2,9,10,-34,-43,-8,-19, 
  /* [4][0][][] */ 22,72,-22,50,-46,8,-76,127, 10,3,-25,0,76,62,-35,-7, -5,27,10,-47,-30,-69,-52,-22, 
  /* [4][1][][] */ 6,58,16,33,7,16,14,-45, 102,49,46,46,78,73,-31,7, -44,32,18,-90,-28,-73,3,-19, 
  /* [4][2][][] */ 10,-16,-12,-53,-8,61,67,33, 111,9,50,85,110,15,10,42, -37,26,19,-34,-19,-57,-11,-22, 
  /* [5][0][][] */ 55,83,98,78,47,22,77,-1, 71,-26,2,59,-8,-32,46,-26, -17,-9,30,20,-46,-41,-54,-34, 
  /* [5][1][][] */ 127,-30,51,21,-30,11,20,-16, 26,-25,15,68,33,18,43,-10, 17,-15,0,0,-24,-28,-4,-23, 
  /* [5][2][][] */ 74,45,75,121,11,36,30,-26, 49,25,-3,4,-20,-9,4,-14, -7,-12,26,-20,-34,-39,1,-46, 
  /* [6][0][][] */ 54,-5,43,-77,46,-27,-24,-18, -98,-40,-91,-86,-52,-32,-78,-13, -50,27,42,-27,28,88,-121,39, 
  /* [6][1][][] */ 28,-19,36,-89,52,-30,1,-28, -103,0,-109,-127,-64,-28,-69,-2, -39,15,64,-80,0,29,-100,16, 
  /* [6][2][][] */ 4,14,60,-93,107,-36,-31,-23, -95,-47,-80,-88,-89,-22,-98,-22, -9,3,53,-72,-4,60,-85,47, 
  /* [7][0][][] */ 53,89,38,49,-1,83,-38,-18, -37,7,23,-8,127,-9,16,50, 42,-20,42,-38,-15,-51,5,-26, 
  /* [7][1][][] */ 94,40,19,4,30,74,8,47, 40,-20,25,-11,0,30,-6,-19, 22,-35,31,-4,-7,-56,-14,-39, 
  /* [7][2][][] */ 49,70,22,-38,4,112,-20,1, 27,0,4,90,90,-6,16,47, -6,-21,35,-43,-11,-41,2,-30, 
};
const TfArray<8, float> quant10_scale = { 8, { 0.0045559396967291832, 0.0034120443742722273, 0.0050479262135922909, 0.0046571283601224422, 0.0036441837437450886, 0.0048985355533659458, 0.0054301242344081402, 0.0045552067458629608, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data11[8] = { 91, -9, -69, -11042, -23144, -28207, -110, -21303, };
const TfArray<8, float> quant11_scale = { 8, { 1.5416417227243073e-05, 2.4918221242842264e-05, 1.2554745808301959e-05, 1.4829128303972539e-05, 9.9900362329208292e-06, 7.9671581261209212e-06, 1.076647276931908e-05, 9.1281535787857138e-06, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data12[8*3*3*1] = { 
  /* [0][0][][] */ 6, 105, -109, 
  /* [0][1][][] */ -1, -85, 4, 
  /* [0][2][][] */ 66, -85, -127, 
  /* [1][0][][] */ -127, -18, -20, 
  /* [1][1][][] */ -3, -26, 13, 
  /* [1][2][][] */ -72, 88, -14, 
  /* [2][0][][] */ 70, 76, -127, 
  /* [2][1][][] */ 35, -26, -82, 
  /* [2][2][][] */ 79, 24, -92, 
  /* [3][0][][] */ -84, -43, -50, 
  /* [3][1][][] */ -57, 54, -41, 
  /* [3][2][][] */ 127, 73, 88, 
  /* [4][0][][] */ 127, 27, -9, 
  /* [4][1][][] */ 120, -13, -7, 
  /* [4][2][][] */ 36, 90, -43, 
  /* [5][0][][] */ -40, 127, 55, 
  /* [5][1][][] */ -25, 127, 49, 
  /* [5][2][][] */ -56, 125, 49, 
  /* [6][0][][] */ 78, 127, -33, 
  /* [6][1][][] */ 61, -43, -9, 
  /* [6][2][][] */ -114, -109, 13, 
  /* [7][0][][] */ 74, 60, 127, 
  /* [7][1][][] */ 14, 91, 35, 
  /* [7][2][][] */ -50, 90, -21, 
};
const TfArray<4, int> tensor_dimension12 = { 4, { 8,3,3,1 } };
const TfArray<8, float> quant12_scale = { 8, { 0.0039466028101742268, 0.0063790646381676197, 0.0032140149269253016, 0.0037962568458169699, 0.0025574492756277323, 0.0020395924802869558, 0.0027562170289456844, 0.0023368073161691427, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant5_zero, 0 };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,99,40,1 } };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,40,8 } };
const TfArray<1, float> quant14_scale = { 1, { 0.003446199931204319, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,20,8 } };
const TfArray<1, float> quant16_scale = { 1, { 0.0067750979214906693, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,25,10,8 } };
const TfArray<1, float> quant18_scale = { 1, { 0.013453452847898006, } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,13,5,8 } };
const TfArray<1, float> quant20_scale = { 1, { 0.038550790399312973, } };
const TfLiteAffineQuantization quant20 = { (TfLiteFloatArray*)&quant20_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,7,3,8 } };
const TfArray<2, int> tensor_dimension22 = { 2, { 1,168 } };
const TfArray<2, int> tensor_dimension23 = { 2, { 1,8 } };
const TfArray<1, float> quant23_scale = { 1, { 0.36190125346183777, } };
const TfArray<1, int> quant23_zero = { 1, { 52 } };
const TfLiteAffineQuantization quant23 = { (TfLiteFloatArray*)&quant23_scale, (TfLiteIntArray*)&quant23_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 13 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 13,12,11 } };
const TfArray<1, int> outputs1 = { 1, { 14 } };
const TfLitePoolParams opdata2 = { kTfLitePaddingSame, 2,2, 2,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs2 = { 1, { 14 } };
const TfArray<1, int> outputs2 = { 1, { 15 } };
const TfLiteConvParams opdata3 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs3 = { 3, { 15,10,9 } };
const TfArray<1, int> outputs3 = { 1, { 16 } };
const TfLitePoolParams opdata4 = { kTfLitePaddingSame, 2,2, 2,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs4 = { 1, { 16 } };
const TfArray<1, int> outputs4 = { 1, { 17 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 17,8,7 } };
const TfArray<1, int> outputs5 = { 1, { 18 } };
const TfLitePoolParams opdata6 = { kTfLitePaddingSame, 2,2, 2,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs6 = { 1, { 18 } };
const TfArray<1, int> outputs6 = { 1, { 19 } };
const TfLiteConvParams opdata7 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs7 = { 3, { 19,6,5 } };
const TfArray<1, int> outputs7 = { 1, { 20 } };
const TfLitePoolParams opdata8 = { kTfLitePaddingSame, 2,2, 2,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs8 = { 1, { 20 } };
const TfArray<1, int> outputs8 = { 1, { 21 } };
const TfLiteReshapeParams opdata9 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs9 = { 2, { 21,2 } };
const TfArray<1, int> outputs9 = { 1, { 22 } };
const TfLiteFullyConnectedParams opdata10 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs10 = { 3, { 22,4,3 } };
const TfArray<1, int> outputs10 = { 1, { 23 } };
const TfLiteSoftmaxParams opdata11 = { 1 };
const TfArray<1, int> inputs11 = { 1, { 23 } };
const TfArray<1, int> outputs11 = { 1, { 24 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 1344, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension3, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension3, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension6, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension3, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension6, 576, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension3, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 72, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 31680), (TfLiteIntArray*)&g0::tensor_dimension13, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 31680, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 31680), (TfLiteIntArray*)&g0::tensor_dimension15, 8000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension15, 8000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 8000), (TfLiteIntArray*)&g0::tensor_dimension17, 2000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension17, 2000, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 2000), (TfLiteIntArray*)&g0::tensor_dimension19, 520, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension19, 520, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant20))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 528), (TfLiteIntArray*)&g0::tensor_dimension21, 168, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant20))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 168, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant20))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 176), (TfLiteIntArray*)&g0::tensor_dimension23, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant23))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension23, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[12] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[12] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_CONV_2D, OP_MAX_POOL_2D, OP_CONV_2D, OP_MAX_POOL_2D, OP_CONV_2D, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 25, };
const size_t tflNodes_subgraph_index[] = {0, 12, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  24, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_954506_25_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 25;
  for (size_t i = 0; i < 25; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_954506_25_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_954506_25_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_954506_25_invoke() {
  for (size_t i = 0; i < 12; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_954506_25_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
